title: Raw SAS # the site title

# production settings
#url: "https://rawsas.com" # the base protocol & hostname for your site
#baseurl: "/" # the site root

# staging settings
url: "https://rawsas.github.io" # the base protocol & hostname for your site
baseurl: "" # the site root

gems: [jekyll-paginate]
paginate: 5

exclude: ['CNAME', '*.sublime-*'] # files to ignore when generating the _site folder
